# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main
  
variables:
  DOCKER_BUILDKIT: 1
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: SEVER_PROD
    condition: eq(variables.isMain, true)
    jobs:
      - job: Build_and_push_docker_image_prod
        steps:
        - task: Docker@2
          inputs:
            displayName: Login to PeopleApps Registry
            containerRegistry: 'PeopleApps Registry'
            command: 'login'
        - task: Docker@2
          inputs:
            displayName: Build docker image and push to hub server
            repository: 'csn-wordpress'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'
            tags: | 
                latest
                latest-$(Build.BuildNumber)
        - task: Docker@2
          inputs:
            displayName: close session for registry
            containerRegistry: 'PeopleApps Registry'
            command: 'logout'
